version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_db_pg_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres-db-volume:
