INSECT_LIST = [
    "Abeille",
    "Aeschne",
    "Agrion",
    "Ammophile",
    "Apollon",
    "Argus bleu",
    "Belle-Dame",
    "Blatte américaine",
    "Bombyx du chêne",
    "Bombyx du mûrier",
    "Bourdon",
    "Bupreste",
    "Cafard",
    "Capricorne",
    "Carabe",
    "Cétoine",
    "Charançon",
    "Chrysomèle",
    "Chrysope",
    "Cicadelle",
    "Cigale",
    "Cochenille",
    "Courtilière",
    "Criquet migrateur",
    "Cynips",
    "Cygne",
    "Demoiselle",
    "Demi-deuil",
    "Doryphore",
    "Dytique",
    "Ecaille martre",
    "Ephémère",
    "Flambé",
    "Fourmi rousse",
    "Fourmilion",
    "Frelon",
    "Gendarme",
    "Grand hydrophile",
    "Grand paon de nuit",
    "Grande sauterelle",
    "Grillon des champs",
    "Grillon domestique",
    "Guépe",
    "Guèpe",
    "Gyrin",
    "Hanneton",
    "fiancée",  # ! issue with this one
    "Ichneumon",
    "Lampyre",
    "Libellule",
    "Lichenée",
    "Lucane cerf-volant",
    "Machaon",
    "Mante religieuse",
    "Mouche bleue",
    "Mouche domestique",
    "Moustique",
    "Nécrophore",
    "Nèpe",
    "Notonecte",
    "Oedipode",
    "Paon de jour",
    "Perce-oreille",
    "Perle",
    "Petite tortue",
    "Phalène",
    "Phasme",
    "Phrygane",
    "Piéride du chou",
    "Poisson d'argent",
    "Pou",
    "Puce",
    "Puceron",
    "Punaise des lits",
    "Punaise verte",
    "Ranâtre",
    "Rhinocéros ou orycte",
    "Scolyte",
    "Scarabée sacré",
    "Sialis",
    "Sirex",
    "Sphinx",
    "Staphylin",
    "Taon",
    "Taupin",
    "Ténébrion",
    "Tenthrède",
    "Termite",
    "Tipule",
    "Vulcain",
    "Xylocope",
    "Zygène",
]
