PLANTS_SPECIES_TO_SEARCH = {
    "lowest_common_rank_id": 211194,  # Tracheophyta
    "taxon_list": [
        "Ajonc",
        "Aubépine",
        "Aulne",
        "Bouleau",
        "Buis",
        "Bruyère",
        "Cerisier",
        "Charme",
        "Châtaignier",
        "Chêne",
        "Chèvrefeuille",
        "Cornouiller",
        "Erable",
        "Frêne",
        "Genévrier",
        "Genêt",
        "Gui",
        "Hêtre",
        "Houx",
        "Lierre",
        "Marronnier",
        "Noisetier",
        "Noyer",
        "Orme",
        "Peuplier",
        "Pin maritime",
        "Pin sylvestre",
        "Platane",
        "Poirier",
        "Pommier",
        "Robinier",
        "Ronce",
        "Rosier",
        "Saule",
        "Sorbier",
        "Tilleul",
        "Troène",
    ],
}

PLANTS_FAMILIES = [
    "Amaryllidacées",
    "Apiacées",
    "Astéracées",
    "Brassicacées",
    "Caryophyllacées",
    "Cypéracées",
    "Fabacées",
    "Géraniacées",
    "Iridacées",
    "Juncaceae",
    "Lamiacées",
    "Liliacées",
    "Malvacées",
    "Orchidaceae",
    "Papaveraceae",
    "Poacées",
    "Primulacées",
    "Renonculacées",
    "Rosacées",
    "Rubiacées",
    "Scrophulariacées",
    "Solanaceae",
]
