PLANTS_SPECIES_TO_SEARCH = {
    "lowest_common_rank_id": 211194,  # Tracheophyta
    "taxon": [
        "Ajonc",
        "Aubépine",
        "Aulne",
        "Bouleau",
        "Buis",
        "Bruyère",
        "Cerisier",
        "Charme",
        "Châtaignier",
        "Chêne",
        "Chèvrefeuille",
        "Cornouiller",
        "Erable",
        "Frêne",
        "Genévrier",
        "Genêt",
        "Gui",
        "Hêtre",
        "Houx",
        "Lierre",
        "Marronnier",
        "Noisetier",
        "Noyer",
        "Orme",
        "Peuplier",
        "Pin maritime",
        "Pin sylvestre",
        "Platane",
        "Poirier",
        "Pommier",
        "Robinier",
        "Ronce",
        "Rosier",
        "Saule",
        "Sorbier",
        "Tilleul",
        "Troène",
    ],
}

PLANTS_FAMILIES = {
    "lowest_common_rank_id": None,  # TODO : find common ancestor
    "taxon": [
        "Amaryllidaceae",
        "Apiacées",
        "Astéracées",
        "Brassicacées",
        "Caryophyllacées",
        "Cypéracées",
        "Fabacées",
        "Géraniacées",
        "Iridacées",
        "Juncaceae",
        "Lamiacées",
        "Liliacées",
        "Malvaceae",
        "Orchidaceae",
        "Papaveraceae",
        "Poacées",
        "Primulaceae",
        "Renonculacées",
        "Rosacées",
        "Rubiacées",
        "Scrophulariaceae",
        "Solanaceae",
    ],
}
