PYRENEAN_SPECIES_TO_SEARCH = {
    "lowest_common_rank_id": 47126,  # TODO: check lowest rank_id
    "taxon": [
        "Aegilops",
        "Ail des ours",
        "Alchemille",
        "Alisier blanc",
        "Alliaire",
        "Alysson blanc",
        "Alysson à calices persistants",
        "Asplenium trichomanes",
        "Hepatica nobilis",
        "Arbousier",
        "Asparagus acutifolius",  # Asperge sauvage
        "Astragale de montpellier",
        "Asterolide",
        "Avoine",
        "Badasse",
        "Baguenaudier",
        "Benoîte",
        "Brachipode penné",
        "Braume mou",
        "Brome stérile",
        "Bruyère",
        "Buis",
        "Buplevre ligneux",
        "Calluna vulgaris",
        "Capsella bursa pastoris",
        "Carex",
        "Cardamine des près",
        "Chardon laiteux",
        "Châtaignier commun",
        "Chèvrefeuille",
        "Chicorée sauvage",
        "Cigüe",
        "Cornouiller sanguin",
        "Crataegus monogyna",
        "Cyprès",
        "Dactylis glomerata",
        "Digitale pourpre",
        "Drosera",
        "Erable champêtre",
        "Erable de montpellier",
        "Epiaire droite",
        "Euphorbe d'Irelande",
        "Euphorbe petit cyprès",
        "Euphorbe réveil matin",
        "Fenouil",
        "Filaire",
        "Aphyllanthe de montpellier",
        "Fougère-aigle",
        "Fragon faux houx",
        "Frêne",
        "Gaillet blanc",
        "Gaillet gratteron",
        "Garance voyageuse",
        "Genévrier de phenicie",
        "Genêt à balais",
        "Spartier à tige de jonc",
        "Genêt poilu",
        "Genêt scorpion",
        "Genista tinctoria",
        "Geranium robertianum",
        "Géranium des bois",
        "Glaieul d'italie",
        "Grande chélidoine",
        "Grémille pourpre",
        "Hellébore fétide",
        "Helianthemum apeninum",
        "Helichrysum",
        "Hêtre",
        "Hippocrepis comosa",
        "Houx",
        "Janciance de corps",
        "Juperinus communis",
        "Jupinerus oxycedrus",
        "Laurier palme",
        "Lautier corniculée",
        "Lin sauvage",
        "Liseron",
        "Lunetière",
        "Luzerne",
        "Mélique",
        "Molène bouillon-blanc",
        "Mouron des oiseaux",
        "Muscari à toupet",
        "Myosotis",
        "Nerprun alaterne",
        "Rhamnus saxatilisNoisetier",
        "Olivier",
        "Ophrys apifera",
        "Ophrys lutea",
        "Orchis pyramidal",
        "Orge des rats",
        "Orme",
        "Orpin acre",
        "Orthie dioique",
        "Panicaut champêtre",
        "Pâturin des près",
        "Peuplier noir",
        "Pêcher",
        "Pédiculaire des pyrénées",
        "Petasite",
        "Petite luzerne",
        "Pervenche",
        "Phacelie",
        "Pin à crochet",
        "Pin d'Alep",
        "Sanguisorba minor",  # Pimprenelle
        "Pistachier lentisque",
        "Pistachier térébinthe",
        "Plantain queue de lièvre",
        "Plantain sauvage",
        "Polygala",
        "Polytricum formosum",
        "Potentille",
        "Pulsatila vulgaris",
        "Reine des près",
        "Reine marguerite",
        "Renoncule âcre",
        "Renoncule bulbeuse",
        "Renoué du japon",
        "Reseda lutea",
        "Robinier faux-acacia",
        "Rosa canina",
        "Ruta graveolens",
        "Rumex",
        "Salepareille",
        "Salsifis",
        "Saponaria",
        "Saponaire",
        "Sauge",
        "Saule marsault",
        "Saxifrage des murailles",
        "Scabieuse",
        "Serpolet",
        "Sphaigne",
        "Silène",
        "Sisymbre",
        "Stellaire",
        "Sureau noir",
        "Sureau yèble",
        "Teucrium",
        "Thymus vulgaris",
        "Tamier commun",
        "Troène commun",
        "Urosperme",
        "Vesce craca",
        "Vicia sativa",
        "Vigne",
        "Vipérine",
        "Véronique de perse",
        "Véronique petit chêne",
    ],
}

PYRENEAN_FAMILIES_TO_SEARCH = {
    "rank_filter": ["family"],
    "taxon": [
        "Boraginaceae",
        "Caryophylaceae",
        "Cistaceae",
        "Cucurbitaceae",
        "Joncasseae",
        "Nymphaeaceae",
        "Papaveraceae",
        "Saxifragaceae",
    ],
}
