"""test

Revision ID: 9f6268758ef1
Revises: 
Create Date: 2024-05-31 13:07:09.493792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f6268758ef1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxon',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specie', sa.String(length=255), nullable=False),
    sa.Column('genus', sa.String(length=255), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('order', sa.String(length=255), nullable=True),
    sa.Column('class_', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxon_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('taxon_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxon_type_id'], ['taxon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxon_type',
    sa.Column('taxon_id', sa.Integer(), nullable=False),
    sa.Column('config_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_type_id'], ['config_type.id'], ),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxon.id'], ),
    sa.PrimaryKeyConstraint('taxon_id', 'config_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxon_type')
    op.drop_table('taxon_photo')
    op.drop_table('taxon')
    op.drop_table('config_type')
    # ### end Alembic commands ###
